version: '3'
services:
  app:
    build:
      context: .
      args:
        - REACT_APP_RADICALE_USERNAME=${REACT_APP_RADICALE_USERNAME}
        - REACT_APP_RADICALE_PASSWORD=${REACT_APP_RADICALE_PASSWORD}
        - REACT_APP_RADICALE_URL=${REACT_APP_RADICALE_URL}
    ports:
      - "80:80"